map_type: costmap

obstacle_range: 1.0
raytrace_range: 2.0

transform_tolerance: 0.2

robot_radius: 0.15
cost_scaling_factor: 10.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: scan, marking: true, clearing: true}
